#! /bin/sh

sxhkd &

# wm config
bspc config border_width         4
bspc config window_gap 20

bspc config split_ratio          0.50

bspc config focus_follows_pointer true

bspc monitor -d 1 2 3 4 5 

# rules
bspc rule -a Zathura state=tiled
bspc rule -a "Genymotion Player" state=floating
bspc rule -a "fl.exe" state=tiled

inactive=$(xrdb -query | grep background | cut -d':' -f2 | sed 's/	//g')
# active=$(xrdb -query | grep foreground | cut -d':' -f2 | sed 's/	//g')
# bspc config normal_border_color "$inactive"
# bspc config focused_border_color "$active"
# bspc config presel_feedback_color "$active"
bspc config normal_border_color "$inactive"
bspc config focused_border_color "$inactive"
bspc config presel_feedback_color "$inactive"

# startup
~/.config/polybar/launch.sh &
picom -b &
~/.fehbg

# BSPC RULEs for Specific Windows

bspc rule -a termite desktop=^1 follow on 
bspc rule -a firefox desktop=^2 follow on
bspc rule -a Chromium desktop=^2 follow on
bspc rule -a Code desktop=^3 follow on
bspc rule -a Skype desktop=^4 follow on
bspc rule -a Spotify desktop=^5 follow on

# mpv --loop --wid=0 ~/Downloads/d.gif
dunst &
# feh-blur -d &
pgrep xflux || xflux -l 43.36 -g 1.26 &
udiskie &
pkill 2bspwm ; 2bspwm

